spring.application.name=torneo
# ========================
# DATABASE
# ========================
spring.datasource.url=jdbc:postgresql://localhost:5433/torneo
spring.datasource.username=postgres
spring.datasource.password=postgres

# ========================
# JPA / HIBERNATE
# ========================
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.hbm2ddl.import_files_sql_extractor=org.hibernate.tool.schema.internal.script.MultiLineSqlScriptExtractor
# ========================
# SERVER
# ========================
server.port=8080

# ========================
# THYMELEAF
# ========================
spring.thymeleaf.cache=false

# ========================
# MESSAGES (validazione)
# ========================
spring.messages.basename=messages/messages
spring.messages.encoding=UTF-8